### ISSUE TITLE
WLAlertHelper createAlertControllerForReason without reason and pass Text dynamically

### ISSUE THREAD

**Issue by umair2ooo** [leetmorry/WLHelpers#1]
Hi,

WLAlertHelper createAlertControllerForReason,
how to do, without reason and pass Text dynamically from anywhere ?

For Example,
[WLAlertHelper createAlertControllerForReason:@"This text will be dynamic, NOT Pre-Defined in Alert.JSON"];

**Comment by leetmorry** [comment]
@umair2ooo   
  
You can add a placeholder alert in your Alerts.json file, which will look like this:  
  
```
"1": {
        "reason" : "DynamicReason",
        "title": "%@",
        "body": "%@"
    },
```  

```  
Optionally define the enum with your alert reasons
enum {
    DynamicReason = 1,
}
```  
  
And use the following method:  
```[WLAlertHelper createAlertControllerForReason:DynamicReason titleArguments:@[@"Your dynamic title"] bodyArguments:@[@"Your dynamic body"] delegate:nil];```

**Comment by umair2ooo** [comment]
It works :-)
Thanks
